name: Build IS Browser

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          ./gradlew client:assembleDebug

      - name: Store APK file
        uses: actions/upload-artifact@v2
        with:
          name: is-browser 
          path: |
              ./client/build/outputs/apk/debug/client-debug.apk
