name: Library unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Library tests
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          ./gradlew internal-storage-file-provider:test

